const system_menu = [
  { 'p': '/', 'template': 'home' },
  { 'p': 'booking_report', 'template': 'booking_report', 'title': 'รายงานห้องพัก' },
  { 'p': 'building', 'template': 'building', 'title': 'บันทึกข้อมูลอาคาร' },
  { 'p': 'building-edit', 'template': 'config_building_edit' },
  { 'p': 'rm_ins', 'template': 'room_insert', 'title': 'เพิ่มข้อมูลห้องพัก' },
  { 'p': 'rm_edit', 'template': 'room_edit', 'title': 'แก้ไขข้อมูลห้องพัก' },
  { 'p': 'rm_m', 'template': 'room_m', 'title': 'จัดการห้องพัก' },
  { 'p': 'm_slide', 'template': 'manage_slide', 'title': 'จัดการภาพโฆษณา' },
  { 'p': 'list-room', 'template': 'list_room' },
  { 'p': 'booking_room', 'template': 'booking_room', 'title': 'สำรวจห้องพัก' },
  { 'p': 'payment', 'template': 'payment','title':'การชำระเงิน เพิ่มบัญชีธนาคาร' },
  { 'p': 'qrcode', 'template': 'qrcode','title':'ช่องทางการชำระเงินแบบ (QRCode)' },
  { 'p': 'social_contact', 'template': 'social_contact', 'title': 'ช่องการติดตามข้อมูล' },
  { 'p': 'company_contact', 'template': 'company_contact' },
  { 'p': 'logo', 'template': 'logo', 'title': 'ปรับแต่งไอคอน และ โลโก้' },
  { 'p': 'meta', 'template': 'meta', 'title': 'Meta SEO' },
  { 'p': 'user-admin', 'template': 'user_admin' },
  { 'p': 'admin-insert', 'template': 'user_admin_insert' },
  { 'p': 'admin-edit', 'template': 'user_admin_edit' },
  { 'p': 'room-about', 'template': 'room_about', 'title': 'ข้อมูลเกี่ยวกับห้องพัก' },
  { 'p': 'rental_m', 'template': 'rental_m', 'title': 'จัดการข้อมูลการเช่าพัก' },
  { 'p': 'rental_mly', 'template': 'rental_monthly','title':'การเช่าพักแบบรายเดือน' },
  { 'p': 'rental_dly', 'template': 'rental_daily' ,'title':'การเช่าพักแบบรายวัน'},
  { 'p': 'additional_m', 'template': 'additional_manage' ,'title':'จัดการข้อมูลการชำระการค่าน้ำประปา และค่าไฟฟ้า'},
  { 'p': 'electricity_config', 'template': 'electricity_config' },
  { 'p': 'additional_transt', 'template': 'additional_transaction','title':'ข้อมูลการชำระการค่าน้ำประปา และค่าไฟฟ้า' },
  { 'p': 'officer_m', 'template': 'officer_manage','title':'ข้อมูลผู้แล เจ้าหน้าที่ และ พนักงาน' },
  { 'p': 'officer_role', 'template': 'officer_role','title':'จัดการบทบาท หน้าที่ผู้แล เจ้าหน้าที่ และ พนักงาน' },
  { 'p': 'profile', 'template': 'profile' ,'title':'ข้อมูลส่วนตัว'},
  { 'p': 'daily', 'template': 'daily' },
  { 'p': 'cf_pay', 'template': 'confirm_payment', 'title': 'ยืนยันการชำระเงิน' },
  { 'p': 'checkin', 'template': 'checkin', 'title': 'เช็คอิน-เข้าพัก' },
  { 'p': 'checkin_isvalid', 'template': 'checkin_isvalid' },
  { 'p': 'promotion', 'template': 'promotion','title':'โปรโมชั่น' },
  { 'p': 'sys_config', 'template': 'system_config','title':'การกำหนดค่าตัวอักษรระบบ' },
  { 'p': 'sys_font', 'template': 'system_config_font','title':'การกำหนดค่าตัวอักษร' },
  { 'p': 'pdf', 'template': 'pdf', 'title': 'ไฟล์รายงาน - PDF' },
  { 'p': 'member', 'template': 'member', 'title': 'สมาชิก' },
]
module.exports = { system_menu }